# Project Constants

# Inference Parameters
INPUT_WIDTH = 512
INPUT_HEIGHT = 288
CONFIDENCE_THRESHOLD = 0.5

# Tracking Parameters
MAX_DISAPPEARED = 40
MAX_DISTANCE = 200.0
BUFFER_SIZE = 2500
FPS_DEFAULT = 30.0

# Ball Size Parameters
BALL_RADIUS_DEFAULT = 10.0
BALL_RADIUS_MIN = 3
BALL_RADIUS_MAX = 40

# Reel Parameters
REEL_ASPECT_RATIO = 9 / 16
SMOOTHING_WINDOW = 11
